// Regenerates the "Biggest sales" ticker in index.html from the Griffey guide's data.
// Run: node build-strip.js   (reads ../griffey-cards, never writes to it)
const fs = require('fs');
const path = require('path');

const GRIFFEY = path.join(__dirname, '..', 'griffey-cards');
const SITE = 'https://griffeycardprices.com';
const N = 24;

const src = fs.readFileSync(path.join(GRIFFEY, 'index.html'), 'utf8');
const m = src.match(/const DATA\s*=\s*(\{[\s\S]*?\n\s*\};)/);
const DATA = eval('(' + m[1].replace(/;\s*$/, '') + ')');
const IMG = JSON.parse(fs.readFileSync(path.join(GRIFFEY, 'card-images.json'), 'utf8'));

const slug = s => s.toLowerCase().replace(/&/g, 'and').replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
const money = n => '$' + Number(n).toLocaleString('en-US');
const esc = s => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/"/g, '&quot;');

// best-priced grade per card, photos only, one entry per card
const rows = [];
for (const [year, sets] of Object.entries(DATA)) {
  for (const s of sets) {
    for (const c of s.subsets) {
      const im = IMG[`${year}|${s.set}|${c.name}`];
      if (!im) continue;
      const grades = [['PSA 10', c.psa10], ['PSA 9', c.psa9], ['PSA 8', c.psa8], ['Raw', c.raw]].filter(g => g[1]);
      if (!grades.length) continue;
      const [grade, val] = grades.sort((a, b) => b[1] - a[1])[0];
      rows.push({ year, set: s.set, name: c.name, grade, val, file: im.file, alt: im.alt || '' });
    }
  }
}
rows.sort((a, b) => b.val - a.val);
const top = rows.slice(0, N);

const card = p =>
  `<a class="tk" href="${SITE}/${p.year}/${slug(p.set.replace(/^\d{4}\s+/, ''))}/">` +
  `<div class="tk-img"><img src="${SITE}/img/cards/${p.file}" alt="${esc(p.alt)}" loading="lazy"></div>` +
  `<div class="tk-body"><div class="tk-name">${esc(p.set)} ${esc(p.name)}</div>` +
  `<div class="tk-row"><span class="tk-grade">${p.grade}</span><span class="tk-price">${money(p.val)}</span></div></div></a>`;

const track = top.map(card).join('');
const html = `<!-- strip:start (generated by build-strip.js) -->
<div class="ticker" aria-label="Biggest tracked Griffey sales"><div class="ticker-track">${track}${track}</div></div>
<!-- strip:end -->`;

const page = path.join(__dirname, 'index.html');
let out = fs.readFileSync(page, 'utf8');
if (!/<!-- strip:start[\s\S]*?<!-- strip:end -->/.test(out)) throw new Error('strip markers not found in index.html');
out = out.replace(/<!-- strip:start[\s\S]*?<!-- strip:end -->/, html);
fs.writeFileSync(page, out);
console.log(`strip: ${top.length} cards, ${money(top[top.length - 1].val)} – ${money(top[0].val)}`);
